#Pls swap out this join message and leave message

join.message: "Welcome &player&, thanks for joining!" #0 will be no message

join.feed: true
join.tpspawn: true
join.setfullhealth: true
join.give.speed.for.30.seconds: true
pvp.kill_bonus_effects: true