name: Custom_SMP_Plugin
version: '1.0-SNAPSHOT'
main: io.sniperjohnny.github.custom_smp_plugin.Custom_SMP_Plugin
api-version: '1.21'


commands:
  enchant:
    permission: "smpplugin.enchant"
    description: "enchants the item in your mainhand"
    aliases:
      - e
  gm:
    permission: "smpplugin.gamemode"
    description: "lets you do /gm1- 1 for creative and so on."
    aliases:
      - gamemode
  fly:
    permission: "smpplugin.fly"
    description: "lets you fly"
    aliases:
      - flying
      - f
  smite:
    permission: "smpplugin.smite"
    description: "lets you choose who gets hit by lightning"
    aliases:
      - sm
      - electrocute
  revive:
    permission: "smpplugin.revive"
    description: "lets you choose who gets hit by lightning"
    aliases:
      - res
      - resurrect
  unban:
    permission: "smpplugin.unban"
    description: "lets you unban an Player"
  revivebeaconrecipe:
    description: "shows the recipe for the revive beacon"
    aliases:
      - resrecipe
      - reciperes
      - reviverecipe
      - reciperevive
  lives:
    description: lets you see your remaining lives
    aliases:
      - seelives